# 데이터 분석 라이브러리
## 1. Numpy
- Numpy (Numeric+Python) : 과학/수학/통계연산과 관련한 함수들의 집합
- 정형데이터의 기본이되는 형태로 초기 데이터 분석에 많이 사용
- 현재는 비정형데이터 전처리 및 분석에 주로 사용

In [1]:
import numpy as np #라이브러리 (모듈) 호출

In [2]:
list1 = [6,5,4,3,2,7] #일반적인 Python list 형태
# list1.mean() : Numpy -> 여러가지 통계 연산들이 가능 하지만,
# Numpy 라이브러리의 통계량을 계산하는 함수를 쓰려면, Numpy 라이브러리에서 사용하는
# 자료구조를 이용해야 함

In [3]:
# 배열(array)
data1 = np.array(list1)
data1

array([6, 5, 4, 3, 2, 7])

In [4]:
data1.mean

<function ndarray.mean>

In [5]:
type(data1) #파이썬의 list와 동일한 특성/ 수학/과학연산에 필요한 차원 구조를 구성

numpy.ndarray

In [6]:
# 정수를 차례로 나열해 array 구성하고자 할 때
[x for x in range(1,10)]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(10) # 0부터 10이전 정수까지

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(2,10, dtype='float') # 2부터 시작하여 10이전까지 수를 정수형태로 생성

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
np.arange(10, 11, 0.1) # np.arange(시작수, 마지막 다음 수, 간격)

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9])

In [14]:
# 특정 범위 내 데이터 수를 지정해 array 구성
data2 = np.linspace(10, 20, 5) #np.linspace(시작수, 마지막 수, 지정된 데이터 갯수)
data2

array([10. , 12.5, 15. , 17.5, 20. ])

In [15]:
data2.ndim
# ndim : 해당 배열의 차원 수를 표현
# Scalar0 (Tensor 0) / Vector 1 (Sequence) / Matrix 2 / Tensor 3 / Tensor 4 / ...

# 소괄호가 없는 함수 -> 해당 데이터의 자료구조의 구조적인 특성을 확인

1

In [18]:
# matrix 형태로 array를 구성하는 경우
# 리스트를 이용해 Matrix를 구성
m1 = [ [1,2,3],[4,5,6],[7,8,9]] # 이중 리스트 구성
data3 = np.array(m1)
data3 #행 (row) x 열 (column)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
data3.ndim

2

In [20]:
data4 = np.array([[1,2],[3,4],[5,6]]) # 3x2 행렬 (3행 2열)
data5 = np.array([[10,20],[100,100],[500,500]])

In [21]:
# Matrix의 경우 행과 열의 정보가 일치할 때, 서로 연산이 가능
data4 + data5

array([[ 11,  22],
       [103, 104],
       [505, 506]])

In [22]:
(data4 + data5) **2

array([[   121,    484],
       [ 10609,  10816],
       [255025, 256036]])

In [23]:
data4.shape # 특정 Matrix의 (data frame) 행과 열 개수를 확인

(3, 2)

In [32]:
# Matrix 자료에 대한 Indexing (특정 위치의 데이터를 찾는 것)
data5 = np.array([['A','B','C'],['D','E','F'],['G','H','I']], dtype='<U2')
data5 # '<U1'는 한 글자로 되어 있는 문자열의 의미 (두 글자 <U2 / 세글자 <U3 / ...)

array([['A', 'B', 'C'],
       ['D', 'E', 'F'],
       ['G', 'H', 'I']], dtype='<U2')

In [33]:
data5[0] #특정 행 확인

array(['A', 'B', 'C'], dtype='<U2')

In [34]:
data5[0,1] #특정 위치의 값을 확인(특정 행x열의 값을 확인)

'B'

In [35]:
# 특정 열을 확인하고자 할 때
data5[:, 0] # 모든 행에 위치한 0번째 열을 출력 -> 0번째 열을 확인

array(['A', 'D', 'G'], dtype='<U2')

In [36]:
# 특정 위치에 다른 값을 선언 (값을 변경 가능)
data5[0,0] = 'Z'

In [37]:
data5

array([['Z', 'B', 'C'],
       ['D', 'E', 'F'],
       ['G', 'H', 'I']], dtype='<U2')

In [38]:
data5[0] = ['A1','A2','A3'] # 특정 행 값 자체를 바꾸고자 할 때

In [39]:
data5 # 만약 글자수를 늘리고 싶다면, data5 생성 부분에서 지정해주어야 함

array([['A1', 'A2', 'A3'],
       ['D', 'E', 'F'],
       ['G', 'H', 'I']], dtype='<U2')

In [41]:
# 기존의 Matrix에 새로운 행을 추가
np.vstack([data5, ['M1','M2','M3']])

array([['A1', 'A2', 'A3'],
       ['D', 'E', 'F'],
       ['G', 'H', 'I'],
       ['M1', 'M2', 'M3']], dtype='<U2')

In [43]:
# 새로운 열 추가
np.hstack( [data5, [['Q1'],['Q2'],['Q3']]])

array([['A1', 'A2', 'A3', 'Q1'],
       ['D', 'E', 'F', 'Q2'],
       ['G', 'H', 'I', 'Q3']], dtype='<U2')

In [44]:
# Reshape (재구조화 함수)
# Vector를 Matrix로 구현하거나, Matrix를 다른 형태로 변환
data6 = np.array([10,20,30,40])
data6

array([10, 20, 30, 40])

In [46]:
data6.reshape(2,2) # Vector 값을 2x2 행렬로 변환

array([[10, 20],
       [30, 40]])

In [47]:
data7 = np.linspace(1, 100, 9)
data7

array([  1.   ,  13.375,  25.75 ,  38.125,  50.5  ,  62.875,  75.25 ,
        87.625, 100.   ])

In [48]:
data7.reshape(3,3)

array([[  1.   ,  13.375,  25.75 ],
       [ 38.125,  50.5  ,  62.875],
       [ 75.25 ,  87.625, 100.   ]])

In [50]:
data8 = np.arange(0,10).reshape(2,5)
data8

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
data8.reshape(5,2) # 정방형이 아닌 행렬로 변환

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
data7.reshape(-1,1) # 하나의 Vector를 nx1 의 Matrix로 변환

array([[  1.   ],
       [ 13.375],
       [ 25.75 ],
       [ 38.125],
       [ 50.5  ],
       [ 62.875],
       [ 75.25 ],
       [ 87.625],
       [100.   ]])

In [55]:
# Matrix에 여러 통계량을 계산
data9 = np.random.randn(2,3) # 2x3 행렬에 난수로 구성된 Matrix 생성
data9

array([[-0.04534691,  0.75892035,  0.59657627],
       [-0.18501151, -0.55950419, -0.87265208]])

In [56]:
data9.sum()

-0.3070180655490282

In [58]:
data9.sum(axis=1) # 행 단위로 값을 계산

array([ 1.31014972, -1.61716778])

In [59]:
data9.sum(axis=0) # 열 단위로 값을 계산

array([-0.23035842,  0.19941616, -0.27607581])

In [60]:
data9.mean(axis=0)

array([-0.11517921,  0.09970808, -0.13803791])

In [61]:
data9.max(axis=0)

array([-0.04534691,  0.75892035,  0.59657627])

## 2. Pandas (Panel + Datasets)

- **Pandas의 자료구조**
- Series (순열) : Numpy Array를 기반으로, 정형 데이터분석을 위해 구성된 Index-Value 형식의 자료구조 (순서-값)

In [62]:
import pandas as pd

In [63]:
s1 = pd.Series([100,200,300,50,700])
s1
# 시리즈는 하나의 데이터 타입만 갖는 자료구조
# 하나의 데이터 타입만 갖는 것이 통계 연산 및 정형데이터 관리에 있어서 매우 유리
# (정형데이터의 효율성과 일관성을 유지하기 위한 규칙 -> RDB 관계형 데이터 베이스)

0    100
1    200
2    300
3     50
4    700
dtype: int64

In [64]:
s1.index
# index라는 데이터의 순서 구조를 가지며, Series 형태로 선언하면 자동으로 index 부여됨

RangeIndex(start=0, stop=5, step=1)

In [66]:
s1.values # Series의 값을 출력하면, Numpy 의 Array 배열의 구조를 하고 있음

array([100, 200, 300,  50, 700])

In [67]:
# 시리즈 indexing
s1[0] # index 내의 값을 대괄호에 입력하면, 해당 인덱스 위치의 값을 출력

100

In [68]:
s1[1:3]

1    200
2    300
dtype: int64

In [69]:
s1[0] = 2000 #특정 인덱스에 있는 값을 다른 값으로 바꾸고자 할 때
s1

0    2000
1     200
2     300
3      50
4     700
dtype: int64

In [70]:
# 다른 값을 제거
s1.drop(1) # 실제로 없애는 것은 아님
# inplace = True 특정 값을 제거한 결과를 변수에 적용
# 많이 선호하지 않는 방법
# 분석을 하다보면 제거한 값이 필요할 때가 있기 때문

0    2000
2     300
3      50
4     700
dtype: int64

In [73]:
s2 = s1.drop(4) #값을 제거할 땐, 제거된 결과를 다른 변수로 선언하여 사용
s2

0    2000
1     200
2     300
3      50
dtype: int64

In [75]:
s2[4] = 500 # 새로운 값을 추가

In [76]:
s2

0    2000
1     200
2     300
3      50
4     500
dtype: int64

In [77]:
# 통계량 계산 또한 쉽게 수행 가능
s2.sum()

3050

In [78]:
s2.mean()

610.0

In [79]:
# Series의 Index는 자동으로 부여되지만, 특정 원하는 값으로 Index를 지정가능
s3 = pd.Series([100,200,300,400], index = ['1st','2nd','3rd','4th'])
s3

1st    100
2nd    200
3rd    300
4th    400
dtype: int64

In [80]:
s3['1st']
# Pandas 내 다양한 함수들을 적용하면, 결과값이 Series 형태로 출력이 될 때,
# Index 값이 숫자가 아닌 형태로 오는 경우가 있음 ! -> 활용

100

In [81]:
s3.index

Index(['1st', '2nd', '3rd', '4th'], dtype='object')

In [82]:
# 딕셔너리 형태로도 시리즈를 구성할 수 있음
s4 = pd.Series({'name':'홍길동', 'age':29, 'gender':'male', 'job':'분석가'})
s4

name       홍길동
age         29
gender    male
job        분석가
dtype: object

- **Data Frame** : Index-Column-Value로 구성되어 있는 자료구조
- 정형데이터의 기본구조와 동일한 형태로, Pandas 라이브러리에서 Excel, CSV, SQL과 같은 형태의 자료를 다루고 처리하기 위해 구성

In [83]:
# 데이터 프레임 구성
df = pd.DataFrame([100,200,300,400]) # D, F는 대문자
df

0
0  100
1  200
2  300
3  400

In [84]:
df.values

array([[100],
       [200],
       [300],
       [400]])

In [86]:
df1 = pd.DataFrame(data= [[100,200,300,400,500], [40,80,120,160,180]],
                  columns = ['A','B','C','D','E'], index=['1st','2nd'])
df1

A    B    C    D    E
1st  100  200  300  400  500
2nd   40   80  120  160  180

In [87]:
# DataFrame의 Indexing
df1['A'] # 특정 Column을 확인할 때, 수행 결과가 Series 형태로 나오게 된다.
# 하나의 DataFrame은 여러 개의 Seires로 구성되어 있다.

1st    100
2nd     40
Name: A, dtype: int64

In [88]:
df1[['A','B']] #DataFrame내 여러 Column을 동시에 Indexing 할 땐, 대괄호 2개
# 대괄호 한 개 -> 하나의 데이터프레임 내에 있는 Column을 시리즈로 출력 -> 두 개 이상의 Colum이 못옴
# 대괄호 두 개 -> 하나의 데이터프레임 내에 있는 Column을 프레임 형태로 출력

A    B
1st  100  200
2nd   40   80

In [91]:
df1[['A']]

A
1st  100
2nd   40

In [95]:
# 딕셔너리 구조를 이용해서 데이터 프레임을 구성
pd.DataFrame(data={'장르': ['발라드','락','인디'],
                   '아티스트': ['아이유','서태지','웨이브'],
                   '노래제목': ['너랑나','교실이데아','A']})

장르 아티스트   노래제목
0  발라드  아이유    너랑나
1    락  서태지  교실이데아
2   인디  웨이브      A

# 기술적 데이터 분석 (DDA)

- 데이터를 가져와 데이터의 기본정보를 파악
- 데이터의 구조와 타입을 확인
- 비즈니스 목표에 부합하는 목표변수(Y, Target, Label, Ouput / 문제 해결에 있어서 데이터상 가장 핵심적인 Column) <-> 설명변수(X, Feature, Column, Input) 확인
- 기술통계량을 파악 (평균/중위수/분산/...)

**01_Data.csv**
- 사무용품을 렌탈하는 업체에서 한명의 고객이 계약한 렌탈 계약건에 대해 한줄씩 정리된 데이터

In [97]:
# 데이터 불러오기
df1 = pd.read_csv('01_Data.csv')
df1

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
0          1   66758234         렌탈          일반계약    영업방판  2022-05-05    60   
1          2   66755948         렌탈          교체계약    영업방판  2023-02-19    60   
2          3   66756657         렌탈          일반계약  홈쇼핑/방송  2022-02-27    60   
3          4   66423450        멤버십        멤버십3유형     재계약  2022-05-12    12   
4          5   66423204        멤버십        멤버십3유형     재계약  2022-05-09    12   
...      ...        ...        ...           ...     ...         ...   ...   
51296  51298   66579515         렌탈        프로모션계약   대형마트A  2022-02-28    60   
51297  51299   66799558         렌탈          일반계약   대형마트A  2022-03-31    60   
51298  51300   66799197         렌탈        프로모션계약    영업방판  2022-03-31    39   
51299  51301   66792778         렌탈          일반계약  홈쇼핑/방송  2023-02-05    60   
51300  51302   66799607         렌탈          일반계약  홈쇼핑/방송  2022-04-23    60   

      Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
0              CMS        DES-1         96900            개인  42.0      경기도   
1             카드이체        DES-1        102900            개인  39.0      경기도   
2              CMS        DES-1         96900            개인  48.0      경기도   
3              CMS        DES-1         66900            개인  39.0      경기도   
4              CMS        DES-1         66900            개인  60.0      경기도   
...            ...          ...           ...           ...   ...      ...   
51296          CMS       DES-3A         96900            개인  47.0      경기도   
51297          CMS        DES-1         96900            개인  42.0      경기도   
51298         카드이체          ERA        120900            개인  65.0    서울특별시   
51299         카드이체        DES-1         96900            개인  54.0    서울특별시   
51300          CMS        DES-1         96900            개인  53.0    서울특별시   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank    Bank  
0          경기도  계약확정              0           없음     여자          9.0   새마을금고  
1          경기도  계약확정              0           없음     남자          2.0    현대카드  
2          경기도  계약확정              0           없음     여자          8.0    우리은행  
3          경기도  계약확정              0           없음     남자          5.0  농협회원조합  
4          경기도  기간만료             12           있음     남자          8.0  농협회원조합  
...        ...   ...            ...          ...    ...          ...     ...  
51296      경기도  계약확정              0           없음     남자          NaN    기업은행  
51297      경기도  계약확정              0           없음     여자          8.0   새마을금고  
51298    서울특별시  계약확정              0           없음     여자          1.0    롯데카드  
51299    서울특별시  계약확정              0           없음     여자          2.0    롯데카드  
51300    서울특별시  계약확정              0           없음     여자          8.0    신한은행  

[51301 rows x 20 columns]

**데이터의 구조와 타입**

- 정형 데이터(Index-Column-Value)의 구조와 타입
    - Index : 데이터의 순서
        - 데이터의 개수를 확인
        - 데이터의 개수에 따라 분석의 방법이 달라질 수 있음 (가설검정)
    - Column : 데이터의 항목
        - 각 항목 별 데이터의 타입 확인
        - 데이터의 타입에 따라 분석의 방법이 달라짐!
            - 연속형 : 숫자데이터 (int/float)
            - 범주형 : 문자데이터 (object)
            - 순서형 : 시간 데이터 -> Work Week (datetime)
    - Value : 데이터의 값
        - 데이터의 형식 (Format) 확인
        - 원시자료설명서 / DB설계서 / 변수정의서 확인
        - 결측값(Missing Value) : 데이터 수집이나 처리 과정에서 누락이나 오류로 인해 
                                발생한 비어있는 값 (None / NaN / NA / Null / inf ...)

In [98]:
# 항목 확인
df1.columns

Index(['Index', 'Member_ID', 'Sales_Type', 'Contract_Type', 'Channel',
       'Datetime', 'Term', 'Payment_Type', 'Product_Type', 'Amount_Month',
       'Customer_Type', 'Age', 'Address1', 'Address2', 'State',
       'Overdue_count', 'Overdue_Type', 'Gender', 'Credit_Rank', 'Bank'],
      dtype='object')

In [99]:
# 인덱스 확인
df1.index

RangeIndex(start=0, stop=51301, step=1)

In [100]:
# 행과 열 확인
df1.shape

(51301, 20)

In [102]:
df1.info() #데이터의 구조와 타입을 한꺼번에 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51301 entries, 0 to 51300
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Index          51301 non-null  int64  
 1   Member_ID      51301 non-null  int64  
 2   Sales_Type     51301 non-null  object 
 3   Contract_Type  51301 non-null  object 
 4   Channel        51301 non-null  object 
 5   Datetime       51301 non-null  object 
 6   Term           51301 non-null  int64  
 7   Payment_Type   51301 non-null  object 
 8   Product_Type   51301 non-null  object 
 9   Amount_Month   51301 non-null  int64  
 10  Customer_Type  51299 non-null  object 
 11  Age            44329 non-null  float64
 12  Address1       51299 non-null  object 
 13  Address2       51299 non-null  object 
 14  State          51301 non-null  object 
 15  Overdue_count  51301 non-null  int64  
 16  Overdue_Type   51301 non-null  object 
 17  Gender         51301 non-null  object 
 18  Credit

# 데이터 전처리

- 기본적인 데이터 핸들링 기법
    - 데이터 추출(행단위/열단위)
    - 데이터 정렬(오름차순/내림차순)
    - 데이터 요약
    - 데이터 필터
    - 데이터 병합
    - 데이터 재구조화
    - 시간 데이터 처리
    - 파생변수 생성 ...

**데이터 추출 및 저장**

In [105]:
# 데이터 추출 (행단위 추출)
df1.head(3) # head(n) : 상위 n개의 데이터를 추출 (공백 - 5개 출력)

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
0      1   66758234         렌탈          일반계약    영업방판  2022-05-05    60   
1      2   66755948         렌탈          교체계약    영업방판  2023-02-19    60   
2      3   66756657         렌탈          일반계약  홈쇼핑/방송  2022-02-27    60   

  Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
0          CMS        DES-1         96900            개인  42.0      경기도   
1         카드이체        DES-1        102900            개인  39.0      경기도   
2          CMS        DES-1         96900            개인  48.0      경기도   

  Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank   Bank  
0      경기도  계약확정              0           없음     여자          9.0  새마을금고  
1      경기도  계약확정              0           없음     남자          2.0   현대카드  
2      경기도  계약확정              0           없음     여자          8.0   우리은행

In [107]:
df1.tail() # 하위 n개의 데이터를 추출

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
51296  51298   66579515         렌탈        프로모션계약   대형마트A  2022-02-28    60   
51297  51299   66799558         렌탈          일반계약   대형마트A  2022-03-31    60   
51298  51300   66799197         렌탈        프로모션계약    영업방판  2022-03-31    39   
51299  51301   66792778         렌탈          일반계약  홈쇼핑/방송  2023-02-05    60   
51300  51302   66799607         렌탈          일반계약  홈쇼핑/방송  2022-04-23    60   

      Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
51296          CMS       DES-3A         96900            개인  47.0      경기도   
51297          CMS        DES-1         96900            개인  42.0      경기도   
51298         카드이체          ERA        120900            개인  65.0    서울특별시   
51299         카드이체        DES-1         96900            개인  54.0    서울특별시   
51300          CMS        DES-1         96900            개인  53.0    서울특별시   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank   Bank  
51296      경기도  계약확정              0           없음     남자          NaN   기업은행  
51297      경기도  계약확정              0           없음     여자          8.0  새마을금고  
51298    서울특별시  계약확정              0           없음     여자          1.0   롯데카드  
51299    서울특별시  계약확정              0           없음     여자          2.0   롯데카드  
51300    서울특별시  계약확정              0           없음     여자          8.0   신한은행

In [108]:
# 특정 범위 내의 데이터를 확인
df1.iloc[50:60]   # iloc(index location) : 특정 범위 내 데이터를 확인

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
50     51   66758548         렌탈          일반계약    영업방판  2022-03-30    60   
51     52   66758162         렌탈         패키지계약  홈쇼핑/방송  2022-10-02    60   
52     53   66758162         렌탈         패키지계약  홈쇼핑/방송  2022-05-03    60   
53     54   66590304         렌탈        프로모션계약    영업방판  2021-12-31    60   
54     55   66670488         렌탈        프로모션계약    영업방판  2022-04-02    60   
55     56   25856039         렌탈          교체계약    영업방판  2022-04-30    60   
56     57   25869517         렌탈        프로모션계약    영업방판  2022-07-21    60   
57     58   66757967         렌탈        프로모션계약    영업방판  2022-08-20    60   
58     59   66260467         렌탈          교체계약    영업방판  2022-02-15    60   
59     60   66758899         렌탈         패키지계약   전문매장H  2022-07-29    60   

   Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
50          CMS        DES-1         96900            개인  57.0    서울특별시   
51         카드이체        DES-1         98400            개인  50.0    서울특별시   
52         카드이체        DES-2         80400            개인  50.0    서울특별시   
53          CMS        DES-2         90900            개인  43.0    서울특별시   
54          CMS        DES-1         96900            개인  34.0    서울특별시   
55          CMS        DES-1         96900           사업자   NaN      경상도   
56         가상계좌        DES-1         96900           사업자   NaN      경상도   
57         카드이체        DES-1        105900            개인  37.0      경상도   
58          CMS        DES-1         96900            개인  42.0      경상도   
59          CMS        DES-1         81900            개인  67.0      경상도   

   Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank   Bank  
50    서울특별시  계약확정              0           없음     남자          4.0   국민은행  
51    서울특별시  계약확정              0           없음     남자          5.0   국민카드  
52    서울특별시  계약확정              0           없음     남자          5.0   국민카드  
53    서울특별시  계약확정              0           없음     남자          4.0   신한은행  
54    서울특별시  계약확정              0           없음     여자          4.0   우리은행  
55    부산광역시  계약확정              0           없음     여자          NaN  농협중앙회  
56    부산광역시  계약확정              0           없음     여자          NaN    NaN  
57      경상도  계약확정              0           없음     여자          5.0   롯데카드  
58      경상도  계약확정              0           없음     여자          1.0   우리은행  
59      경상도  계약확정              0           없음     남자          2.0   대구은행

In [110]:
# 열 단위 추출
df1['Amount_Month'] #하나의 열을 출력

0         96900
1        102900
2         96900
3         66900
4         66900
          ...  
51296     96900
51297     96900
51298    120900
51299     96900
51300     96900
Name: Amount_Month, Length: 51301, dtype: int64

In [113]:
df1[['Amount_Month','Channel','Datetime']] #여러개의 열을 확인

Amount_Month Channel    Datetime
0             96900    영업방판  2022-05-05
1            102900    영업방판  2023-02-19
2             96900  홈쇼핑/방송  2022-02-27
3             66900     재계약  2022-05-12
4             66900     재계약  2022-05-09
...             ...     ...         ...
51296         96900   대형마트A  2022-02-28
51297         96900   대형마트A  2022-03-31
51298        120900    영업방판  2022-03-31
51299         96900  홈쇼핑/방송  2023-02-05
51300         96900  홈쇼핑/방송  2022-04-23

[51301 rows x 3 columns]

In [117]:
#데이터를 저장 (to_excel / to_csv : 확장자 명을 잘 작성)
df1[['Amount_Month','Channel','Datetime']].head(100).to_excel('result.xlsx')

**데이터 정렬**

In [120]:
df1.sort_values(by='Amount_Month') # 오름차순 (숫자가 낮은 수부터 정렬)

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
35768  35770   66784964        멤버십        멤버십2유형   전문매장H  2022-02-06    36   
43022  43024   66792946        멤버십        멤버십2유형   전문매장H  2023-06-30    36   
49993  49995   66796388        멤버십        멤버십2유형   전문매장H  2023-03-25    36   
33803  33805   66783630        멤버십        멤버십2유형   전문매장H  2023-07-28    36   
45246  45248   66793779        멤버십        멤버십2유형   전문매장H  2022-07-15    36   
...      ...        ...        ...           ...     ...         ...   ...   
5399    5400   25742182         렌탈        프로모션계약    영업방판  2022-05-17    39   
49896  49898   25731710         렌탈        프로모션계약    영업방판  2022-09-29    39   
49897  49899   25731710         렌탈        프로모션계약    영업방판  2022-12-05    39   
28147  28149   25704137         렌탈        프로모션계약    전단홍보  2022-07-24    39   
38497  38499   25734005         렌탈        프로모션계약    영업방판  2022-06-04    39   

      Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
35768          무통장        DES-1         54603            개인   NaN      경기도   
43022          무통장        DES-1         54603            개인   NaN      전라도   
49993          무통장        DES-1         54603            개인   NaN    서울특별시   
33803          무통장        DES-1         54603            개인   NaN      경기도   
45246          무통장        DES-1         54603            개인   NaN    서울특별시   
...            ...          ...           ...           ...   ...      ...   
5399           CMS          MMC        215700           사업자   NaN      경기도   
49896         가상계좌          MMC        215700           사업자   NaN      경기도   
49897         가상계좌          MMC        215700           사업자   NaN      경기도   
28147          CMS          MMC        215700           사업자   NaN      경상도   
38497          CMS          MMC        215700           사업자  58.0      전라도   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank   Bank  
35768      경기도  계약확정              0           없음     여자          NaN    NaN  
43022    광주광역시  계약확정              0           없음     여자          NaN    NaN  
49993    서울특별시  계약확정              0           없음     여자          NaN    NaN  
33803    인천광역시  계약확정              0           없음     여자          NaN    NaN  
45246    서울특별시  계약확정              0           없음     여자          NaN    NaN  
...        ...   ...            ...          ...    ...          ...    ...  
5399       경기도  계약확정              1           있음     여자          NaN   신한은행  
49896      경기도  계약확정              0           없음     여자          NaN    NaN  
49897      경기도  계약확정              0           없음     여자          NaN    NaN  
28147      경상도  계약확정              0           없음     여자          NaN   국민은행  
38497      전라도  계약확정              0           없음     남자          1.0  농협중앙회  

[51301 rows x 20 columns]

In [121]:
df1.sort_values(by = 'Amount_Month', ascending = False)

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
19773  19775   25740247         렌탈        프로모션계약    전단홍보  2022-11-13    39   
28147  28149   25704137         렌탈        프로모션계약    전단홍보  2022-07-24    39   
19413  19415   25710320         렌탈        프로모션계약    영업방판  2023-01-28    39   
19412  19414   25710321         렌탈        프로모션계약    영업방판  2022-09-14    39   
37522  37524   25733781         렌탈        프로모션계약    영업방판  2023-07-02    39   
...      ...        ...        ...           ...     ...         ...   ...   
45304  45306   66793756        멤버십        멤버십2유형   전문매장H  2022-10-06    36   
50428  50430   66797402        멤버십        멤버십2유형   전문매장H  2022-12-26    36   
45302  45304   66793342        멤버십        멤버십2유형   전문매장H  2022-04-02    36   
41153  41155   66790864        멤버십        멤버십2유형   전문매장H  2022-02-15    36   
39373  39375   66788207        멤버십        멤버십2유형   전문매장H  2023-05-11    36   

      Payment_Type Product_Type  Amount_Month Customer_Type  Age Address1  \
19773         가상계좌          MMC        215700           사업자  NaN      경상도   
28147          CMS          MMC        215700           사업자  NaN      경상도   
19413          CMS          MMC        215700           사업자  NaN      경기도   
19412          CMS          MMC        215700           사업자  NaN      경기도   
37522          CMS          MMC        215700           사업자  NaN      경기도   
...            ...          ...           ...           ...  ...      ...   
45304          무통장        DES-1         54603            개인  NaN      충청도   
50428          무통장        DES-1         54603            개인  NaN      경기도   
45302          무통장        DES-1         54603            개인  NaN      강원도   
41153          무통장        DES-1         54603            개인  NaN      경기도   
39373          무통장        DES-1         54603            개인  NaN      제주도   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank  Bank  
19773      경상도  계약확정              0           없음     여자          NaN   NaN  
28147      경상도  계약확정              0           없음     여자          NaN  국민은행  
19413      경기도  계약확정              0           없음     여자          NaN  기업은행  
19412      경기도  계약확정              0           없음     여자          NaN  기업은행  
37522      경기도  계약확정              0           없음     여자          NaN  기업은행  
...        ...   ...            ...          ...    ...          ...   ...  
45304      충청도  계약확정              0           없음     여자          NaN   NaN  
50428      경기도  계약확정              0           없음     여자          NaN   NaN  
45302      강원도  계약확정              0           없음     여자          NaN   NaN  
41153      경기도  계약확정              0           없음     여자          NaN   NaN  
39373      제주도  계약확정              0           없음     여자          NaN   NaN  

[51301 rows x 20 columns]

In [124]:
# 여러 가지 항목에 대해 정렬하고자 할 때
df1.sort_values(by = ['Amount_Month','Overdue_count'], ascending=False)

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
44838  44840   25732681         렌탈        프로모션계약    영업방판  2023-04-12    39   
44839  44841   25732681         렌탈        프로모션계약    영업방판  2023-04-18    39   
44840  44842   25732681         렌탈        프로모션계약    영업방판  2023-06-01    39   
5399    5400   25742182         렌탈        프로모션계약    영업방판  2022-05-17    39   
19412  19414   25710321         렌탈        프로모션계약    영업방판  2022-09-14    39   
...      ...        ...        ...           ...     ...         ...   ...   
51210  51212   66799109        멤버십        멤버십2유형   전문매장H  2022-09-03    36   
51277  51279   66799700        멤버십        멤버십2유형   전문매장H  2022-02-23    36   
51280  51282   66799156        멤버십        멤버십2유형   전문매장H  2022-03-09    36   
51284  51286   66799094        멤버십        멤버십2유형   전문매장H  2022-02-23    36   
51290  51292   66798812        멤버십        멤버십2유형   전문매장H  2023-01-27    36   

      Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
44838          CMS          MMC        215700           사업자  51.0      경상도   
44839          CMS          MMC        215700           사업자  51.0      경상도   
44840          CMS          MMC        215700           사업자  51.0      경상도   
5399           CMS          MMC        215700           사업자   NaN      경기도   
19412          CMS          MMC        215700           사업자   NaN      경기도   
...            ...          ...           ...           ...   ...      ...   
51210          무통장        DES-1         54603            개인   NaN      경상도   
51277          무통장        DES-1         54603            개인   NaN      경기도   
51280          무통장        DES-1         54603            개인   NaN      전라도   
51284          무통장        DES-1         54603            개인   NaN    서울특별시   
51290          무통장        DES-1         54603            개인   NaN      경기도   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank  Bank  
44838      경상도  계약확정              2           있음     여자          NaN   우체국  
44839      경상도  계약확정              2           있음     여자          NaN   우체국  
44840      경상도  계약확정              2           있음     여자          NaN   우체국  
5399       경기도  계약확정              1           있음     여자          NaN  신한은행  
19412      경기도  계약확정              0           없음     여자          NaN  기업은행  
...        ...   ...            ...          ...    ...          ...   ...  
51210    부산광역시  계약확정              0           없음     여자          NaN   NaN  
51277    인천광역시  계약확정              0           없음     여자          NaN   NaN  
51280    광주광역시  계약확정              0           없음     여자          NaN   NaN  
51284    서울특별시  계약확정              0           없음     여자          NaN   NaN  
51290      경기도  계약확정              0           없음     여자          NaN   NaN  

[51301 rows x 20 columns]

In [128]:
# 월 랜탈 비용은 높지만, 연체건수는 낮은 데이터를 추출
df1.sort_values(by = ['Amount_Month','Overdue_count'], ascending=[False, True]).head(100).to_excel('result2.xlsx')
#월 랜탈비용이 높고 연체건수는 낮은 상위 100개의 계약 명단을 엑셀로 저장

# 개별미션 (2주차 1일)

- 아래의 미션을 Jupyter Notebook으로 풀이 후 [File] - [Download as] - [HTML] 저장 제출
- 제출 양식 : [하나은행_데이터] 홍길동_개별 미션 (2주차 1일)
- 처음 풀이 시, 30분 정도 구글링 및 Chat GPT없이 풀이

1. 5의 배수로 구성된 9개의 데이터를 생성하여, Numpy Matrix 3x3 행렬로 만든 뒤, 첫번째 행(row)의 합과 평균을 계산하는 함수 생성
    - Matrix 는 아래와 같이 생성
|    |    |    |
|----|----|----|
| 5  | 10 | 15 |
| 20 | 25 | 30 |
| 35 | 40 | 45 |

In [145]:
data1 = np.array([5,10,15,20,25,30,35,40,45])
data1_1 = data1.reshape(3,3)
data1_1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [148]:
data1_1.sum(axis=1)[0]
data1_1.mean(axis=1)[0]

10.0

---------------------------------

2. 두개의 값을 입력받아 두 값 사이의 10개의 데이터를 일정 간격으로 생성해, Vector 형태로 출력하는 함수를 생성

In [179]:
data2 = input('띄어쓰기로 구분하여 두 개의 값을 입력하세요.')
input_list = data2.split(' ')
num1 = float(data2.split(' ')[0])
num2 = float(data2.split(' ')[1])

# 특정 범위 내 데이터 수 지정해 생성
np.linspace(num1, num2, 10)

띄어쓰기로 구분하여 두 개의 값을 입력하세요.30 40


array([30.        , 31.11111111, 32.22222222, 33.33333333, 34.44444444,
       35.55555556, 36.66666667, 37.77777778, 38.88888889, 40.        ])

---------------------------------

3. 학생의 이름과 국어점수, 영어점수, 수학점수를 입력받아 Pandas의 DataFrame 형태로 구성하는 함수를 생성

In [143]:
data3 = input('띄어쓰기로 구분하여 학생의 이름, 국어점수, 영어점수, 수학점수를 입력하세요.')
input_list2=data3.split(' ')
name = data3.split(' ')[0]
score1 = input_list2[1]
score2 = input_list2[2]
score3 = input_list2[3]

df3 = pd.DataFrame(data = [[score1, score2,score3]], columns = ['국어','영어','수학'],
                  index = [name])
df3

띄어쓰기로 구분하여 학생의 이름, 국어점수, 영어점수, 수학점수를 입력하세요.홍길동 30 40 50


국어  영어  수학
홍길동  30  40  50

---------------------------------

4. 01_Data.csv 파일을 가져와 df1으로 선언하고, 아래의 미션을 수행
해당 데이터에서 고객의 계약 명단 중 우수 고객을 찾고자 한다. df1 데이터에서 월랜탈 비용(Amount_month)가 높고, 연령이 낮은(Age) 상위 50명의 고객 계약 명단을 추출해 result3.xlsx 저장

In [150]:
df1 = pd.read_csv('01_Data.csv')

#월랜탈 비용 높고, 연령 낮은 고객 / 상위 50명
df1.sort_values(by = ['Amount_Month','Age'], ascending=[False, True]).head(50).to_excel('result3.xlsx')

---------------------------------

5. 젊은 고객들을 대상으로 마케팅 대상을 수립하기 위해, 연령이 낮은 100명의 계약 명단을 추출하여, df1_young 변수로 선언하고, 데이터의 구조와 타입을 확인

In [164]:
df1_young = df1.sort_values(by = 'Age',ascending=True).head(100)
type(df1_young) #구조 및 타입 확인

pandas.core.frame.DataFrame

---------------------------------

6. df1_young 데이터와 df1 데이터의 월랜탈비용(Amount_Month)의 평균을 계산하고, 두 값의 차이를 계산

In [162]:
mean1 = df1_young['Amount_Month'].mean()
mean2 = df1['Amount_Month'].mean()
print(mean1)
print(mean2)

diff = abs(mean1-mean2)
diff

94191.0
93994.97428900021


196.02571099979104

---------------------------------

7. df1_young에서 월랜탈비용이 높고 연체건수(Overdue_count)가 낮은 순서대로 정렬해, result_young.xlsx로 저장하시오.

In [166]:
df1_young.sort_values(by=['Amount_Month','Overdue_count'], ascending = [False, True]).to_excel('result_young.xlsx')

---------------------------------

    8. 본사에서 매출관리를 위해 연체가 높은 고객들을 확인하여 관리하고자 한다. 연체건수가 높은 순서대로 정렬하고, 상위 100명의 고객의 연령(Age)의 최대값과 최소값을 확인하고 신용등급(Credit_Rank)의 평균을 계산

In [168]:
df8 = df1.sort_values(by=['Overdue_count'],ascending=False).head(100)
df8

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
2705    2706   66760494         렌탈         패키지계약  홈쇼핑/방송  2023-06-29    60   
3093    3094   66679489         렌탈        프로모션계약    영업방판  2023-06-20    60   
3782    3783   66603883         렌탈          일반계약    영업방판  2022-10-27    60   
5846    5847   66762531         렌탈         패키지계약    영업방판  2023-07-29    60   
5845    5846   66762531         렌탈         패키지계약    영업방판  2023-07-10    60   
...      ...        ...        ...           ...     ...         ...   ...   
16450  16452   66769597         렌탈         패키지계약    영업방판  2022-12-19    60   
28383  28385   66778083         렌탈          일반계약    영업방판  2022-02-12    60   
18813  18815   66770854         렌탈        프로모션계약   전문매장Z  2022-04-24    60   
28189  28191   66778622         렌탈        프로모션계약    영업방판  2022-08-18    39   
32550  32552   66782724         렌탈          일반계약    영업방판  2022-09-15    60   

      Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
2705           CMS        DES-2         81900            개인  52.0      전라도   
3093           CMS       DES-3A         90900            개인  58.0    서울특별시   
3782           CMS        DES-1        111900            개인  38.0      전라도   
5846           CMS        DES-2         89400            개인  27.0      충청도   
5845           CMS        DES-1        134400            개인  27.0      충청도   
...            ...          ...           ...           ...   ...      ...   
16450          CMS        DES-1         98400            개인  50.0      강원도   
28383          CMS        DES-1         96900            개인  46.0      충청도   
18813          CMS        DES-1         96900            개인  34.0      경상도   
28189          CMS          ERA        120900            개인  59.0      경상도   
32550          CMS       DES-3A        102900            개인  44.0      경상도   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank    Bank  
2705       전라도  계약확정             15           있음     남자          8.0    우리은행  
3093     서울특별시  계약확정             15           있음     여자          4.0    우리은행  
3782       전라도  계약확정             15           있음     여자          7.0   농협중앙회  
5846     대전광역시  계약확정             15           있음     남자          5.0    하나은행  
5845     대전광역시  계약확정             15           있음     남자          5.0    하나은행  
...        ...   ...            ...          ...    ...          ...     ...  
16450      강원도  계약확정             13           있음     여자          7.0  농협회원조합  
28383      충청도  계약확정             13           있음     남자          7.0     우체국  
18813      경상도  계약확정             13           있음     여자          7.0    부산은행  
28189    대구광역시  계약확정             13           있음     남자          7.0    외환은행  
32550    울산광역시  계약확정             13           있음     여자          6.0  농협회원조합  

[100 rows x 20 columns]

In [172]:
max_age = df8['Age'].max()
min_age = df8['Age'].min()
mean_credit = df8['Credit_Rank'].mean()

print(f'연령의 최대값:{max_age}, 연령의 최소값: {min_age}, 신용등급 평균:{mean_credit}')

연령의 최대값:85.0, 연령의 최소값: 26.0, 신용등급 평균:6.945205479452055


---------------------------------

9. 매출관리 부서 A씨는 매주 해당 데이터를 받아 계약금액이 높은 1000개의 계약명단의 평균값을 계산하고 있다. 이 업무를 자동화하기 위해, 월랜탈비용이 높은 1000개의 데이터를 추출하여, 해당 데이터의 월랜탈비용의 평균을 계산하는 함수를 만드시오.

In [176]:
def solution9():
    df9 = df1.sort_values(by = 'Amount_Month', ascending = False).head(1000)
    mean_Amount_Month = df9['Amount_Month'].mean()
    return mean_Amount_Month

solution9()

144188.25